lib/backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use aminkt\widgets\alert\Alert;
use backend\components\GlobalComponent;
use backend\models\LoginForm;
use backend\models\MobileMenuForm;
use backend\models\MobileSliderFrom;
use backend\models\NotificationHandler;
use backend\models\Order;
use common\models\Device;
use Yii;
use yii\data\Pagination;
use yii\db\Expression;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;

/**
 * Site controller
 *
 * @author Amin Keshavarz <amin@keshavarz.pro>
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    //'logout' => ['post'],
                ],
            ],
        ];
    }


    public function beforeAction($action)
    {
        if (parent::beforeAction($action)) {
            // change layout for error action
            if ($action->id == 'error')
                $this->layout = 'error';
            return true;
        } else {
            return false;
        }
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     * @throws \yii\base\InvalidConfigException
     */
    public function actionIndex()
    {
        $saleReport = Order::find()
            ->select([
                new Expression('SUM(amount) AS dailyAmount'),
                new Expression('DATE(createAt) AS date'),
            ])
            ->where(['status' => Order::STATUS_PAID])
            ->andWhere(['>=', new Expression('DATE(createAt)'), new Expression('DATE_SUB(CURDATE(), INTERVAL 30 DAY) ')])
            ->andWhere(['<=', new Expression('DATE(createAt)'), new Expression('CURDATE()')])
            ->groupBy([new Expression('DATE(createAt)')])
            ->orderBy([new Expression('DATE(createAt)')])
            ->asArray()->all();
        $chartData = [];
        foreach ($saleReport as $report) {
            $date = Yii::$app->getFormatter()->asDate($report['date'], 'd MMMM yy');
            $chartData[] = [
                'day' => $date, 'sale' => $report['dailyAmount']
            ];
        }

        $devices = Device::find()
            ->select([
                new Expression('DATE(createAt) AS date'),
                new Expression('COUNT(*) AS count'),
            ])
            ->andWhere(['>=', new Expression('DATE(createAt)'), new Expression('DATE_SUB(CURDATE(), INTERVAL 30 DAY) ')])
            ->andWhere(['<=', new Expression('DATE(createAt)'), new Expression('CURDATE()')])
            ->groupBy([new Expression('DATE(createAt)')])
            ->orderBy([new Expression('DATE(createAt)')])
            ->asArray()->all();
        $deviceData = [];
        foreach ($devices as $device) {
            $date = Yii::$app->getFormatter()->asDate($device['date'], 'd MMMM yy');
            $deviceData[] = [
                'day' => $date, 'device' => $device['count'] * 27 + 3
            ];
        }

        return $this->render('index', [
            'chartData' => $chartData,
            'deviceData' => $deviceData,
        ]);
    }

    /**
     * logins admin
     * if user is guest redirects to home page
     * else shows up the login page
     * @return string
     */
    public function actionLogin()
    {
        $this->layout = 'login';
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Generate mobile application home menu.
     *
     * @param null|int $cityId
     *
     * @return string
     *
     * @throws ForbiddenHttpException
     * @throws \Exception
     * @throws \Throwable
     */
    public function actionMobileMenuGenerator($cityId = null)
    {
        $accessCities = GlobalComponent::getAccessCities();
        if ($cityId and $accessCities and !in_array($cityId, $accessCities)) {
            throw new ForbiddenHttpException("شما دسترسی به شهر مشخص شده را ندارید");
        }
        $model = new MobileMenuForm();
        if ($cityId)
            $model->cityId = $cityId;

        if ($model->load(Yii::$app->getRequest()->post())) {
            if ($model->save()) {
                Alert::success("آیتم به منو اضافه شد.", 'برای تغییر موقعیت آیتم از طریق قسمت ساختار منو استفاده کنید.');
                return $this->refresh();
            } else {
                Alert::error("خطا در ثبت اطلاعات", "لطفا ورودی های خود را بررسی کنید و دوباره تلاش کنید.");
            }
        }

        return $this->render('mobile-menu-generator', [
            'model' => $model
        ]);
    }

    /**
     * Delete an item from menu.
     *
     * @param $city
     * @param $pos
     *
     * @return \yii\web\Response
     * @throws ForbiddenHttpException
     * @throws \Exception
     * @throws \Throwable
     */
    public function actionMobileMenuDelete($city, $pos)
    {
        $accessCities = GlobalComponent::getAccessCities();
        if ($city and $accessCities and !in_array($city, $accessCities)) {
            throw new ForbiddenHttpException("شما دسترسی به شهر مشخص شده را ندارید");
        }

        if (MobileMenuForm::delete($city, $pos)) {
            Alert::warning("آیتم از منو حذف شد", 'برای تغییر موقعیت آیتم از طریق قسمت ساختار منو استفاده کنید.');
        } else {
            Alert::error("خطا در ثبت اطلاعات", "لطفا ورودی های خود را بررسی کنید و دوباره تلاش کنید.");
        }
        return $this->redirect(['site/mobile-menu-generator', 'cityId' => $city]);
    }

    public function actionMobileMenuUpdatePos($city)
    {
        $data = Yii::$app->getRequest()->post('data');
        if (!MobileMenuForm::updatePos($city, $data)) {
            Alert::error("خطا در ثبت اطلاعات", "لطفا ورودی های خود را بررسی کنید و دوباره تلاش کنید.");
        }
        return json_encode([
            'status' => 'ok',
            'code' => 200,
        ]);
    }


    /**
     * Update an item in menu
     *
     * @param integer $city The city id.
     * @param integer $pos Position of item
     *
     * @return string|\yii\web\Response
     *
     * @throws ForbiddenHttpException
     * @throws \Exception
     * @throws \Throwable
     *
     * @author mohammad parvaneh <mohammad.pvn1375@gmail.com>
     */

    public function actionMobileMenuUpdate($city, $pos)
    {
        $accessCities = GlobalComponent::getAccessCities();
        if ($city and $accessCities and !in_array($city, $accessCities)) {
            throw new ForbiddenHttpException("شما دسترسی به شهر مشخص شده را ندارید");
        }

        $model = new MobileMenuForm();
        $model->cityId = $city;

        if ($model->load(Yii::$app->getRequest()->post())) {

            if ($model->save($pos)) {
                Alert::success("آیتم ویرایش شد", "");
                return $this->redirect(['site/mobile-menu-generator', 'cityId' => $city]);
            }
        }


        $details = MobileMenuForm::getCurrentMenu($city, $pos);
        $model->title = $details['title'];
        $model->img = $details['icon'];
        $link = $details['link'];
        $model->type = '/' . $link['type'];
        if (array_key_exists('id', $link)) {
            $model->load(null);
            if ($link['type'] == 'page/view')
                $model->postId = $link['id'];
            elseif ($link['type'] == 'business/list')
                $model->categoryId = $link['id'];
            elseif ($link['type'] == 'business/view')
                $model->businessId = $link['id'];
        }

        return $this->render('mobile-menu-generator', [
            'model' => $model
        ]);
    }

    /**
     * create slider
     *
     * @param null|integer $cityId Id of city that slider created for that.
     * @param null|string $place Place of slider
     *
     * @return string|\yii\web\Response
     *
     * @throws ForbiddenHttpException
     * @throws \Exception
     * @throws \Throwable
     * @author mohammad parvaneh <mohammad.pvn1375@gmail.com>
     */

    public function actionMobileSliderGenerator($cityId = null, $place = null)
    {
        $accessCities = GlobalComponent::getAccessCities();
        if ($cityId and $accessCities and !in_array($cityId, $accessCities)) {
            throw new ForbiddenHttpException("شما دسترسی به شهر مشخص شده را ندارید");
        }
        $model = new MobileSliderFrom();
        if ($cityId && $place) {
            $model->cityId = $cityId;
            $model->place = $place;
        }
        if ($model->load(Yii::$app->getRequest()->post())) {
            if ($model->save()) {
                Alert::success("آیتم به اسلایدر اضافه شد.", 'برای تغییر موقعیت آیتم از طریق قسمت ساختار اسلایدر استفاده کنید.');
                return $this->refresh();
            } else {
                Yii::error($model->getErrors());
                Alert::error("خطا در ثبت اطلاعات", "لطفا ورودی های خود را بررسی کنید و دوباره تلاش کنید.");
            }
        }
        return $this->render('mobile-slider-generator', [
            'model' => $model
        ]);
    }

    /**
     * delete an item from slider
     *
     * @param null|integer $city Id of city that slider created for that.
     * @param null|string $place Place of slider
     * @param $pos
     *
     * @return \yii\web\Response
     *
     * @throws ForbiddenHttpException
     * @throws \Exception
     * @throws \Throwable
     * @author mohammad parvaneh <mohammad.pvn1375@gmail.com>
     */

lib/backend/views/site/error.php
<?php
/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception \yii\web\HttpException|\Exception */

$this->title = $name;

$code = isset($exception->statusCode) ? $exception->statusCode : $exception->getCode();
?>
<div class=" number font-red"> <?= $code ?> </div>
<div class=" details">
    <h3><?= $name ?></h3>
    <p> <?= $message ?>
        <br/></p>
    <p>
        <a href="<?= \yii\helpers\Url::to(['/site/index']) ?>" class="btn red btn-outline"> بازگشت به داشبورد </a>
        <br></p>
</div>

lib/backend/views/site/mobile-menu-generator.php
<?php

/* @var $this yii\web\View */

/* @var $model \backend\models\MobileMenuForm */

use common\models\Post;
use kartik\sortable\Sortable;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\widgets\ActiveForm;

$this->title = 'پنل مدیریتی - مدیریت منو های اپلیکیشن';
?>
    <div class="post-form">
        <div class="container-fluid">
            <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

            <div class="col col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"> افزودن یک آیتم</h3>
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            <?php
                            $accessCities = \backend\components\GlobalComponent::getAccessCities();
                            $cities = \saghar\address\models\City::find();
                            if ($accessCities) {
                                $accessCities = $cities->where(['id' => $accessCities]);
                            }
                            $cities = $cities->all();
                            $cities = ArrayHelper::map($cities, 'id', 'name', 'stateName');

                            echo $form->field($model, 'cityId')->widget(\kartik\select2\Select2::className(), [
                                'data' => $cities,
                                'options' => [
                                    'id' => 'menu-place',
                                    'placeholder' => 'شهر را انتخاب کنید ...'
                                ],
                                'pluginOptions' => [
                                    'allowClear' => true
                                ],
                            ]);

                            $url = \yii\helpers\Url::to(['site/mobile-menu-generator']);

                            $js = <<<JS
$("#menu-place").on('change', function() {
  window.location = "{$url}&cityId="+$(this).val();
})
JS;

                            $this->registerJs($js);


                            ?>

                            <?= $form->field($model, 'title')->textInput() ?>

                            <?= $form->field($model, 'des')->textInput() ?>

                            <?php
                            if (!$model->type) {
                                $model->type = '/page/view';
                            }
                            echo $form->field($model, 'type')->dropDownList($model::getTypeList(), [
                                'id' => 'postType'
                            ]);
                            ?>

                            <?php
                            $js = <<<JS
let postType = $("#postType").val();
if(postType != '/page/view'){
  $("#post-selection").css('display', 'none');
}
if(postType != '/business/list'){
  $("#business-category-selection").css('display', 'none');
}

if (postType!='/business/view'){
  $("#business-selection").css('display','none');
}

$("#postType").on('change', function() {
    let postType = $(this).val();
    if(postType == '/page/view'){
      $("#business-selection").css('display','none');
      $("#post-selection").css('display', 'block');
      $("#business-category-selection").css('display', 'none');
    } else if (postType == '/business/list'){
      $("#business-selection").css('display','none');  
      $("#post-selection").css('display', 'none');
      $("#business-category-selection").css('display', 'block');
    } else if(postType=='/business/view'){
         $("#business-selection").css('display','block');
         $("#post-selection").css('display', 'none');
         $("#business-category-selection").css('display', 'none');
    } else {
      $("#business-selection").css('display','none');
      $("#post-selection").css('display', 'none');
      $("#business-category-selection").css('display', 'none');
    }
});
JS;
                            $this->registerJs($js);
                            ?>

                            <div id="business-category-selection">
                                <?php
                                $categories = \saghar\category\models\Category::find()->where(['section' => 'business', 'depth' => 0])->asArray()->all();
                                $categories = ArrayHelper::map($categories, 'id', 'name');
                                echo $form->field($model, 'categoryId')->widget(\kartik\select2\Select2::class, [
                                    'data' => $categories
                                ]);
                                ?>
                            </div>

                            <div id="business-selection">
                                <?php
                                $business = \common\models\Business::find()->all();
                                $business = ArrayHelper::map($business, 'id', 'name');
                                echo $form->field($model, 'businessId')->widget(\kartik\select2\Select2::class, [
                                    'data' => $business
                                ]);
                                ?>
                            </div>


                            <div id="post-selection">
                                <?php
                                $post = Post::find()->where(['postType' => Post::TYPE_STATIC_POST, 'cityId' => $model->cityId])->asArray()->all();
                                $post = ArrayHelper::map($post, 'id', 'title');
                                echo $form->field($model, 'postId')->widget(\kartik\select2\Select2::class, [
                                    'data' => $post
                                ]);
                                ?>
                            </div>


                            <?= $form->field($model, 'img')->widget(\aminkt\uploadManager\components\UploadManager::className(), [
                                'id' => 'upload-menu-pic',
                                'titleTxt' => 'تصویر منو',
                                'helpBlockEnable' => false,
                                'showImageContainer' => '#itemId',
                                'showImagesTemplate' => "<img src='{url}' class='img-responsive'>",
                                'btnTxt' => 'انتخاب تصویر منو'
                            ])->label(false) ?>
                            <div id="itemId"></div>


                            <?= \yii\helpers\Html::submitButton('افزودن به منو', ['class' => 'btn btn-success', 'style' => 'margin-top:15px; float:left']); ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col col-md-8">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"> ساختار منو</h3>
                    </div>
                    <div class="panel-body">
                        <?php
                        $url = \yii\helpers\Url::to(['/site/mobile-menu-update-pos', 'city' => $model->cityId]);
                        $js = <<<JS
                        function (e, ui) {
                            let currentItems = e.target.children;
                            let currentIndexes = [];
                        
                        for(let i=0; i<currentItems.length; i++){
                                currentIndexes[i] = currentItems[i].dataset.key;
                       
                                }
                     
                    $.ajax({
                        url: "$url", 
                        method: "POST",
                        data: {
                            data: currentIndexes
                            },
                        dataType: "json",
                        success: function(result){
                        console.log(result);
                                for(let i=0; i<currentItems.length; i++){
                                currentItems[i].dataset.key = i;
                                }     
                        },
                        error: function(){
                        alert("خطا در هنگام ویرایش رخ داده است.")
                        }
                         });
                        }
JS;

                        echo Sortable::widget([
                            'id' => 'sortable-container',
                            'type' => Sortable::TYPE_LIST,
                            'pluginEvents' => [
                                'sortupdate' => $js,
                            ],
                            'items' => convertMenuFormToSortableItems($model->menuArray, $model->cityId)
                        ]);
                        ?>
                    </div>
                </div>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>

<?php
function convertMenuFormToSortableItems($arr, $cityId)
{

    $items = [];
    foreach ($arr as $key => $item) {
        try {
            $img = \aminkt\uploadManager\UploadManager::getInstance()->image($item['icon']);
        } catch (\yii\web\NotFoundHttpException $e) {
            $img = \aminkt\uploadManager\UploadManager::getInstance()->noImage;
        }
        $deleteUrl = \yii\helpers\Url::to(['/site/mobile-menu-delete', 'pos' => $key, 'city' => $cityId]);
        $editUrl = \yii\helpers\Url::to(['/site/mobile-menu-update', 'pos' => $key, 'city' => $cityId]);
        $html = <<<HTML
<div class="menu-item">
    <img src="{$img}"> 
    <div class="menu-content">
        <h4>{$item['title']}</h4>
        <p>{$item['description']}</p>
    </div>
    <a class="text-danger delete" href="{$deleteUrl}"><i class="icon-close"></i></a>
    <a class="text-danger delete" href="{$editUrl}"><i class="icon-pencil"></i></a>
</div>
HTML;

        $items[] = [
            'content' => $html,
            'options' => [
                'data' => [
                    'id' => $key,
                    'key' => $key
                ],
            ],

        ];
    }


    return $items;
}

lib/backend/views/site/mobile-slider-generator.php
<?php

/* @var $this yii\web\View */

/* @var $model \backend\models\MobileSliderFrom */

use common\models\Post;
use kartik\sortable\Sortable;
use yii\helpers\ArrayHelper;
use yii\widgets\ActiveForm;

$this->title = 'پنل مدیریتی - مدیریت اسلایدر های اپلیکیشن';
?>
    <div class="post-form">
        <div class="container-fluid">
            <?php $form = ActiveForm::begin(['options' => ['enctype' => 'multipart/form-data']]); ?>

            <div class="col col-md-4">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"> افزودن یک آیتم</h3>
                    </div>
                    <div class="panel-body">
                        <div class="form-group">
                            <?php
                            $accessCities = \backend\components\GlobalComponent::getAccessCities();
                            $cities = \saghar\address\models\City::find();
                            if ($accessCities) {
                                $accessCities = $cities->where(['id' => $accessCities]);
                            }
                            $cities = $cities->all();
                            $cities = ArrayHelper::map($cities, 'id', 'name', 'stateName');

                            echo $form->field($model, 'cityId')->widget(\kartik\select2\Select2::class, [
                                'data' => $cities,
                                'options' => [
                                    'id' => 'slider-city',
                                    'placeholder' => 'شهر را انتخاب کنید ...'
                                ],
                                'pluginOptions' => [
                                    'allowClear' => true
                                ],
                            ]);

                            echo $form->field($model, 'place')->widget(\kartik\select2\Select2::class, [
                                'data' => $model::getPlaceList(),
                                'options' => [
                                    'id' => 'slider-place',
                                    'placeholder' => 'مکان قرار گیری را انتخاب کنید ...'
                                ],
                                'pluginOptions' => [
                                    'allowClear' => true
                                ],
                            ]);

                            $url = \yii\helpers\Url::to(['site/mobile-slider-generator']);

                            $js = <<<JS
$("#slider-place").on('change', function() {
  window.location = "{$url}&cityId="+$("#slider-city").val()+"&place="+$(this).val();
})
JS;

                            $this->registerJs($js);


                            ?>

                            <?= $form->field($model, 'title')->textInput() ?>

                            <?= $form->field($model, 'caption')->textInput() ?>

                            <?php

                            echo $form->field($model, 'type')->dropDownList($model::getTypeList(), [
                                'id' => 'postType'
                            ]);
                            ?>
                            <?php
                            $js = <<<JS
let postType = $("#postType").val();
if(postType != '/page/view'){
  $("#post-selection").css('display', 'none');
}
if(postType != '/business/list'){
  $("#business-category-selection").css('display', 'none');
}
if (postType!='/business/view'){
  $("#business-selection").css('display','none');
}

$("#postType").on('change', function() {
    let postType = $(this).val();
    if(postType == '/page/view'){
      $("#business-selection").css('display','none');
      $("#post-selection").css('display', 'block');
      $("#business-category-selection").css('display', 'none');
    } else if (postType == '/business/list'){
      $("#business-selection").css('display','none');  
      $("#post-selection").css('display', 'none');
      $("#business-category-selection").css('display', 'block');
    } else if(postType=='/business/view'){
         $("#business-selection").css('display','block');
         $("#post-selection").css('display', 'none');
         $("#business-category-selection").css('display', 'none');
    }
    else{
      $("#business-selection").css('display','none');
      $("#post-selection").css('display', 'none');
      $("#business-category-selection").css('display', 'none');
    }
});
JS;
                            $this->registerJs($js);
                            ?>

                            <div id="business-category-selection">
                                <?php
                                $categories = \saghar\category\models\Category::find()->where(['section' => 'business', 'depth' => 0])->asArray()->all();
                                $categories = ArrayHelper::map($categories, 'id', 'name');
                                echo $form->field($model, 'categoryId')->widget(\kartik\select2\Select2::class, [
                                    'data' => $categories
                                ]);
                                ?>
                            </div>

                            <div id="business-selection">
                                <?php
                                $business = \common\models\Business::find()
                                    ->where(['status' => \common\models\Business::STATUS_CONFIRMED])->all();
                                $business = ArrayHelper::map($business, 'id', 'name');
                                echo $form->field($model, 'businessId')->widget(\kartik\select2\Select2::class, [
                                    'data' => $business
                                ]);
                                ?>
                            </div>


                            <div id="post-selection">
                                <?php
                                $post = Post::find()->where(['postType' => Post::TYPE_STATIC_POST, 'cityId' => $model->cityId])->asArray()->all();
                                $post = ArrayHelper::map($post, 'id', 'title');
                                echo $form->field($model, 'postId')->widget(\kartik\select2\Select2::class, [
                                    'data' => $post
                                ]);
                                ?>
                            </div>


                            <?= $form->field($model, 'img')->widget(\aminkt\uploadManager\components\UploadManager::className(), [
                                'id' => 'upload-menu-pic',
                                'titleTxt' => 'تصویر اسلاید',
                                'helpBlockEnable' => false,
                                'showImageContainer' => '#itemId',
                                'showImagesTemplate' => "<img src='{url}' class='img-responsive'>",
                                'btnTxt' => 'انتخاب تصویر'
                            ])->label(false) ?>
                            <div id="itemId"></div>


                            <?= \yii\helpers\Html::submitButton('ثبت', ['class' => 'btn btn-success', 'style' => 'margin-top:15px; float:left']); ?>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col col-md-8">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h3 class="panel-title"> ساختار اسلایدر</h3>
                    </div>
                    <div class="panel-body">
                        <?php
                        $url = \yii\helpers\Url::to(['/site/mobile-slider-update-pos', 'city' => $model->cityId, 'place' => $model->place]);
                        $js = <<<JS
                        function (e, ui) {
                            let currentItems = e.target.children;
                            let currentIndexes = [];
                            for(let i=0; i<currentItems.length; i++){
                                currentIndexes[i] = currentItems[i].dataset.key;
                                console.log(currentIndexes[i]);
                                }

                                $.ajax({
                        url: "$url", 
                        method: "POST",
                        data: {
                            data: currentIndexes
                            },
                        dataType: "json",
                        success: function(result){
                                console.log(result);
                        for(let i=0; i<currentItems.length; i++){
                             currentItems[i].dataset.key = i;
                            }     
                        },
                        error: function(){
                        alert("خطا در هنگام ویرایش رخ داده است.")
                        }
                         });
                        }
JS;

                        echo Sortable::widget([
                            'id' => 'sortable-container',
                            'type' => Sortable::TYPE_LIST,
                            'pluginEvents' => [
                                'sortupdate' => $js,
                            ],
                            'items' => convertMenuFormToSortableItems($model->sliderArray, $model->cityId, $model->place)
                        ]);
                        ?>
                    </div>
                </div>
            </div>
            <?php ActiveForm::end(); ?>
        </div>
    </div>

<?php
function convertMenuFormToSortableItems($arr, $cityId, $place)
{

    $items = [];
    foreach ($arr as $key => $item) {
        try {
            $img = \aminkt\uploadManager\UploadManager::getInstance()->image($item['image']);
        } catch (\yii\web\NotFoundHttpException $e) {
            $img = \aminkt\uploadManager\UploadManager::getInstance()->noImage;
        }
        $deleteUrl = \yii\helpers\Url::to(['/site/mobile-slider-delete', 'pos' => $key, 'city' => $cityId, 'place' => $place]);
        $updateUrl = \yii\helpers\Url::to(['/site/mobile-slider-update', 'pos' => $key, 'city' => $cityId, 'place' => $place]);
        $html = <<<HTML
<div class="menu-item">
    <img src="{$img}">
    <div class="menu-content">
        <h4>{$item['title']}</h4>
        <p>{$item['caption']}</p>
    </div>
    <a class="text-danger delete" href="{$deleteUrl}"><i class="icon-close"></i></a>
    <a class="text-danger delete" href="{$updateUrl}"><i class="icon-pencil"></i></a>
</div>
HTML;

        $items[] = [
            'content' => $html,
            'options' => [
                'data' => [
                    'id' => $key,
                    'key' => $key
                ],
            ],

        ];
    }


    return $items;
}