lib/frontend/controllers/SearchController.php
<?php

namespace frontend\controllers;

use frontend\models\search\Search;

/**
 * Class SearchController
 * Control search actions.
 *
 * @package frontend\controllers
 *
 * @author  Amin Keshavarz <amin@keshavarz.pro>
 */
class SearchController extends \yii\web\Controller
{
    public $layout = 'app';

    /**
     * Main search page.
     *
     * @return string
     *
     * @author Saghar Mojdehi <saghar.mojdehi@gmail.com>
     */
    public function actionIndex()
    {
        $searchModel = new Search();
        $dataProviders = $searchModel->generalSearch(\Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProviders' => $dataProviders
        ]);
    }

    /**
     * Show all searched businesses
     *
     * @return string
     *
     * @author Saghar Mojdehi <saghar.mojdehi@gmail.com>
     */
    public function actionBusinesses()
    {
        $searchModel = new Search();
        $dataProvider = $searchModel->generalBusinessSearch(\Yii::$app->request->queryParams);

        return $this->render('businesses', [
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Show all searched news
     *
     * @return string
     *
     * @author Saghar Mojdehi <saghar.mojdehi@gmail.com>
     */
    public function actionNews()
    {
        $searchModel = new Search();
        $dataProvider = $searchModel->newsSearch(\Yii::$app->request->queryParams);
        return $this->render('news', [
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Show all searched posts
     *
     * @return string
     *
     * @author Saghar Mojdehi <saghar.mojdehi@gmail.com>
     */
    public function actionPosts()
    {
        $searchModel = new Search();
        $dataProvider = $searchModel->postSearch(\Yii::$app->request->queryParams);
        return $this->render('posts', [
            'dataProvider' => $dataProvider
        ]);
    }

    /**
     * Overwrite render to handle ajax requests.
     *
     * @param string $view
     * @param array  $params
     *
     * @return string
     *
     * @author Amin Keshavarz <amin@keshavarz.pro>
     */
    public function render($view, $params = [])
    {
        if (\Yii::$app->getRequest()->isAjax) {
            return $this->renderAjax($view, $params);
        }
        return parent::render($view, $params);
    }
}

lib/frontend/views/search/_news_item.php
<?php
/** @var $model \common\models\Post */ ?>

<div class="row">
    <div class="col s12">
        <a href="<?= \yii\helpers\Url::to(['/news/view', 'id' => $model->id]) ?>">
            <div class="blog-content news-summary">
                <?php if ($model->coverId) : ?>
                    <img src="<?= Yii::$app->getModule('uploadManager')->image($model->coverId, 'thumb') ?>" alt="">
                <?php endif; ?>
                <div class="blog-detailt">
                    <h5> <?= $model->title ?> </h5>
                    <div class="date">
                        <span><i class="fa fa-calendar"></i> <?= $model->getJalaliCreateTime() ?> </span>
                    </div>
                </div>
            </div>
        </a>
    </div>
</div>

lib/frontend/views/search/_post_item.php
<?php
/** @var $model \common\models\Post */
?>

<div class="row">
    <div class="col s12">
        <a href="<?= \yii\helpers\Url::to(['/news/view', 'id' => $model->id]) ?>">
            <div class="blog-content news-summary">
                <?php if ($model->coverId) : ?>
                    <img src="<?= Yii::$app->getModule('uploadManager')->image($model->coverId, 'normal') ?>" alt="">
                <?php endif; ?>
                <div class="blog-detailt">
                    <h5><?= $model->title ?></h5>
                    <?php /*
                    <div class="date">
                        <span><i class="fa fa-calendar"></i> <?= $model->getJalaliCreateTime('yyyy-MM-dd') ?> </span>
                    </div>
                       */ ?>
                </div>
            </div>
        </a>
    </div>
</div>

lib/frontend/views/search/businesses.php
<?php
/** @var $dataProvider \yii\data\ActiveDataProvider */

$this->title = "جستجو در شهر";
?>

<div class="container">
    <div class="title">
        <h3>نتایج جستجو در اصناف</h3>
    </div>
    <div class="businesses">
        <?=
        yii\widgets\ListView::widget([
            'dataProvider' => $dataProvider,
            'summary' => '',
            'itemView' => '/business/_business_item'
        ]);
        ?>
    </div>
</div>

lib/frontend/views/search/index.php
<?php
/* @var $this yii\web\View */

/** @var $searchModel \frontend\models\search\Search */

/** @var $dataProviders \yii\data\ActiveDataProvider[] */

$this->title = "جستجو در شهر";
?>


<div class="container">

    <!-- Search box -->
    <?php $form = yii\widgets\ActiveForm::begin([
        'method' => 'get',
    ]);
    ?>
    <?= $form->field($searchModel, 'search')->textInput(['placeholder' => 'جستجو', 'class' => 'search-input'])->label(false) ?>
    <?= \yii\helpers\Html::submitButton("<i class='fa fa-search'></i>", [
        'class' => 'btn btn-search',

    ]) ?>
    <?php \yii\widgets\ActiveForm::end(); ?>
    <!-- end search box -->

    <br>
    <?php if ($dataProviders['business']->count != 0): ?>
        <br>
        <div class="title">
            <h3>نتایج جستجو در اصناف</h3>
        </div>
        <br>
        <div class="businesses">
            <?php for ($i = 0; $i < 5; $i++): ?>
                <?php if (isset($dataProviders['business']->models[$i])): ?>
                    <div class="row">
                        <div class="col s12">
                            <a href="<?= yii\helpers\Url::to(['/business/view', 'id' => $dataProviders['business']->models[$i]->id]) ?>">
                                <div class="blog-content business-summary">
                                    <?php if ($imgUrl = $dataProviders['business']->models[$i]->getImage(false)) : ?>
                                        <img src="<?= $imgUrl ?>"
                                             alt="">
                                    <?php endif; ?>
                                    <div class="details">
                                        <?php if ($dataProviders['business']->models[$i]->name): ?>
                                            <h5> <?= $dataProviders['business']->models[$i]->name ?> </h5>
                                        <?php endif; ?>
                                        <br>
                                        <?php if ($dataProviders['business']->models[$i]->owner): ?>
                                            <div class="owner">
                                                <span><i class="fa fa-user"></i> &nbsp;<?= $dataProviders['business']->models[$i]->owner->fullName ?> </span>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($dataProviders['business']->models[$i]->getMainPhone()): ?>
                                            <div class="phone">
                                                <span><i class="fa fa-phone"></i> &nbsp;<?= $dataProviders['business']->models[$i]->getMainPhone() ?> </span>
                                            </div>
                                        <?php endif; ?>
                                        <?php if ($dataProviders['business']->models[$i]->getAddress()): ?>
                                            <div class="address">
                                                <span><i class="fa fa-map-signs"></i> &nbsp;<?= $dataProviders['business']->models[$i]->getAddress()->address ?> </span>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                <?php endif; ?>
            <?php endfor; ?>
        </div>
        <?php if ($dataProviders['business']->count > 5): ?>

            <?php if (\Yii::$app->getRequest()->get("Search")): ?>
                <?= yii\helpers\Html::a('بیشتر', ['/search/businesses',
                    "Search[search]" => \Yii::$app->getRequest()->get("Search")['search']],
                    ['class' => 'btn btn-primary']) ?>
            <?php else: ?>
                <?= yii\helpers\Html::a('بیشتر', ['/search/businesses'],
                    ['class' => 'btn btn-primary']) ?>
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>


    <?php if ($dataProviders['news']->count != 0): ?>
        <br>
        <div class="title">
            <h3>نتایج جستجو در اخبار</h3>
        </div>
        <br>
        <div class="news">
            <?php for ($i = 0; $i < 5; $i++): ?>
                <?php if (isset($dataProviders['news']->models[$i])): ?>
                    <div class="row">
                        <div class="col s12">
                            <a href="<?= \yii\helpers\Url::to(['/news/view', 'id' => $dataProviders['news']->models[$i]->id]) ?>">
                                <div class="blog-content news-summary">
                                    <?php if ($dataProviders['news']->models[$i]->coverId) : ?>
                                        <img src="<?= Yii::$app->getModule('uploadManager')->image($dataProviders['news']->models[$i]->coverId, 'thumb') ?>"
                                             alt="">
                                    <?php endif; ?>
                                    <div class="blog-detailt">
                                        <h5> <?= $dataProviders['news']->models[$i]->title ?> </h5>
                                        <div class="date">
                                            <span><i class="fa fa-calendar"></i> &nbsp;&nbsp;<?= $dataProviders['news']->models[$i]->getJalaliCreateTime() ?> </span>
                                        </div>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                <?php endif; ?>
            <?php endfor; ?>
        </div>
        <?php if ($dataProviders['news']->count > 5): ?>
            <?php if (\Yii::$app->getRequest()->get("Search")): ?>
                <?= yii\helpers\Html::a('بیشتر', ['/search/news',
                    "Search[search]" => \Yii::$app->getRequest()->get("Search")['search']],
                    ['class' => 'btn btn-primary']) ?>
            <?php else: ?>
                <?= yii\helpers\Html::a('بیشتر', ['/search/news'],
                    ['class' => 'btn btn-primary']) ?>
            <?php endif; ?>
        <?php endif; ?>
    <?php endif; ?>


    <?php if ($dataProviders['post']->count != 0): ?>
        <br>
        <div class="title">
            <h3>نتایج جستجو در سایر موراد</h3>
        </div>
        <br>
        <div class="posts">
            <?php for ($i = 0; $i < 5; $i++): ?>
                <?php if (isset($dataProviders['post']->models[$i])): ?>
                    <div class="row">
                        <div class="col s12">
                            <a href="<?= \yii\helpers\Url::to(['/news/view', 'id' => $dataProviders['post']->models[$i]->id]) ?>">
                                <div class="blog-content news-summary">
                                    <?php if ($dataProviders['post']->models[$i]->coverId) : ?>
                                        <div class="img-holder">
                                            <img src="<?= Yii::$app->getModule('uploadManager')->image($dataProviders['post']->models[$i]->coverId, 'normal') ?>"
                                                 alt="">
                                        </div>
                                    <?php endif; ?>
                                    <div class="blog-detailt">
                                        <h5><?= $dataProviders['post']->models[$i]->title ?></h5>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                <?php endif; ?>
            <?php endfor; ?>
            <?php if ($dataProviders['post']->count > 5): ?>
                <?php if (\Yii::$app->getRequest()->get("Search")): ?>
                    <?= yii\helpers\Html::a('بیشتر', ['/search/posts',
                        "Search[search]" => \Yii::$app->getRequest()->get("Search")['search']],
                        ['class' => 'btn btn-primary']) ?>
                <?php else: ?>
                    <?= yii\helpers\Html::a('بیشتر', ['/search/posts'],
                        ['class' => 'btn btn-primary']) ?>
                <?php endif; ?>
            <?php endif; ?>
        </div>
    <?php endif; ?>
</div>

lib/frontend/views/search/news.php
<?php
/** @var $dataProvider \yii\data\ActiveDataProvider */
$this->title = "جستجو در شهر";
?>

<div class="container">
    <div class="title">
        <h3>نتایج جستجو در اخبار</h3>
    </div>

    <div class="news">
        <?=
        yii\widgets\ListView::widget([
            'dataProvider' => $dataProvider,
            'summary' => '',
            'itemView' => '_news_item'
        ]);
        ?>
    </div>
</div>

lib/frontend/views/search/posts.php
<?php
/** @var $dataProvider \yii\data\ActiveDataProvider */

$this->title = "جستجو در شهر";
?>

<div class="container">
    <div class="title">
        <h3>نتایج جستجو در پست ها</h3>
    </div>

    <div class="posts">
        <?=
        yii\widgets\ListView::widget([
            'dataProvider' => $dataProvider,
            'summary' => '',
            'itemView' => '_post_item'
        ]);
        ?>
    </div>
</div>